export default {
  SEARCH_BY_LICENSE_NUMBER: 'SEARCH_BY_LICENSE_NUMBER',
  SEARCH_BY_LICENSE_NUMBER_SUCCESS: 'SEARCH_BY_LICENSE_NUMBER_SUCCESS',
  SEARCH_BY_LICENSE_NUMBER_ERROR: 'SEARCH_BY_LICENSE_NUMBER_ERROR',
  FETCH_LICENSE_TYPES: 'FETCH_LICENSE_TYPES',
  FETCH_LICENSE_TYPES_SUCCESS: 'FETCH_LICENSE_TYPES_SUCCESS',
  FETCH_LICENSE_TYPES_ERROR: 'FETCH_LICENSE_TYPES_ERROR',
  FETCH_STATES: 'FETCH_STATES',
  FETCH_STATES_SUCCESS: 'FETCH_STATES_SUCCESS',
  FETCH_STATES_ERROR: 'FETCH_STATES_ERROR',
};
